[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID,NEXT_PUBLIC_SITE_URL,NEXT_PUBLIC_TIER_1_NAME,NEXT_PUBLIC_TIER_2_NAME,NEXT_PUBLIC_TIER_3_NAME,NEXT_PUBLIC_PAYMENT_QR_IMAGE_PATH,NEXT_PUBLIC_FEST_NAME"
SECRETS_SCAN_OMIT_PATHS = ".firebaserc,SETUP_GUIDE.md,GEMINI.md,PLAN.md,README.md,.netlify/.next/server/chunks/s,.lib/cloudinary.ts"