import { Event } from "../types";

export const sportsCatalogue: Event[] = [
  {
    eventId: "cricket",
    indianName: "Cricket",
    englishName: "Cricket Tournament",
    slug: "cricket",
    category: "sports",
    eventDomain: "sports",
    type: "group",
    pricingType: "flat_total",
    fee: 999,
    minTeamSize: 11,
    maxTeamSize: 15,
    isOnline: false,
    tags: ["group", "large-team", "flagship", "sports"],
    shortDescription: "11-a-side cricket tournament",
    description: "",
    imageUrls: [],
    venue: null,
    eventDate: null,
    eventTime: null,
    schedule: null,
    rules: [],
    contactName: null,
    contactPhone: null,
    isAvailable: true,
  },
  {
    eventId: "football",
    indianName: "Football",
    englishName: "Football Tournament",
    slug: "football",
    category: "sports",
    eventDomain: "sports",
    type: "group",
    pricingType: "flat_total",
    fee: 799,
    minTeamSize: 7,
    maxTeamSize: 11,
    isOnline: false,
    tags: ["group", "large-team", "flagship", "sports"],
    shortDescription: "7-a-side football tournament",
    description: "",
    imageUrls: [],
    venue: null,
    eventDate: null,
    eventTime: null,
    schedule: null,
    rules: [],
    contactName: null,
    contactPhone: null,
    isAvailable: true,
  },
  {
    eventId: "basketball",
    indianName: "Basketball",
    englishName: "Basketball Tournament",
    slug: "basketball",
    category: "sports",
    eventDomain: "sports",
    type: "group",
    pricingType: "flat_total",
    fee: 599,
    minTeamSize: 5,
    maxTeamSize: 8,
    isOnline: false,
    tags: ["group", "sports"],
    shortDescription: "5-a-side basketball tournament",
    description: "",
    imageUrls: [],
    venue: null,
    eventDate: null,
    eventTime: null,
    schedule: null,
    rules: [],
    contactName: null,
    contactPhone: null,
    isAvailable: true,
  },
  {
    eventId: "volleyball",
    indianName: "Volleyball",
    englishName: "Volleyball Tournament",
    slug: "volleyball",
    category: "sports",
    eventDomain: "sports",
    type: "group",
    pricingType: "flat_total",
    fee: 599,
    minTeamSize: 6,
    maxTeamSize: 8,
    isOnline: false,
    tags: ["group", "sports"],
    shortDescription: "6-a-side volleyball tournament",
    description: "",
    imageUrls: [],
    venue: null,
    eventDate: null,
    eventTime: null,
    schedule: null,
    rules: [],
    contactName: null,
    contactPhone: null,
    isAvailable: true,
  },
  {
    eventId: "badminton-singles",
    indianName: "Badminton Singles",
    englishName: "Badminton Singles",
    slug: "badminton-singles",
    category: "sports",
    eventDomain: "sports",
    type: "solo",
    pricingType: "flat_total",
    fee: 150,
    minTeamSize: null,
    maxTeamSize: null,
    isOnline: false,
    tags: ["solo", "sports", "under-300"],
    shortDescription: "Singles badminton knockout",
    description: "",
    imageUrls: [],
    venue: null,
    eventDate: null,
    eventTime: null,
    schedule: null,
    rules: [],
    contactName: null,
    contactPhone: null,
    isAvailable: true,
  },
  {
    eventId: "badminton-doubles",
    indianName: "Badminton Doubles",
    englishName: "Badminton Doubles",
    slug: "badminton-doubles",
    category: "sports",
    eventDomain: "sports",
    type: "group",
    pricingType: "flat_total",
    fee: 250,
    minTeamSize: 2,
    maxTeamSize: 2,
    isOnline: false,
    tags: ["group", "small-team", "sports", "under-300"],
    shortDescription: "Doubles badminton knockout",
    description: "",
    imageUrls: [],
    venue: null,
    eventDate: null,
    eventTime: null,
    schedule: null,
    rules: [],
    contactName: null,
    contactPhone: null,
    isAvailable: true,
  },
  {
    eventId: "tt-singles",
    indianName: "Table Tennis Singles",
    englishName: "Table Tennis Singles",
    slug: "tt-singles",
    category: "sports",
    eventDomain: "sports",
    type: "solo",
    pricingType: "flat_total",
    fee: 100,
    minTeamSize: null,
    maxTeamSize: null,
    isOnline: false,
    tags: ["solo", "sports", "under-300"],
    shortDescription: "Singles table tennis knockout",
    description: "",
    imageUrls: [],
    venue: null,
    eventDate: null,
    eventTime: null,
    schedule: null,
    rules: [],
    contactName: null,
    contactPhone: null,
    isAvailable: true,
  },
  {
    eventId: "tt-doubles",
    indianName: "Table Tennis Doubles",
    englishName: "Table Tennis Doubles",
    slug: "tt-doubles",
    category: "sports",
    eventDomain: "sports",
    type: "group",
    pricingType: "flat_total",
    fee: 180,
    minTeamSize: 2,
    maxTeamSize: 2,
    isOnline: false,
    tags: ["group", "small-team", "sports", "under-300"],
    shortDescription: "Doubles table tennis knockout",
    description: "",
    imageUrls: [],
    venue: null,
    eventDate: null,
    eventTime: null,
    schedule: null,
    rules: [],
    contactName: null,
    contactPhone: null,
    isAvailable: true,
  },
];
